:toc: left
:icons: font
:source-highlighter: coderay
:kata_dir: kata5
:sourcedir: ../../../{kata_dir}

== Web Service using Mongo DB

WARNING: Under construction

=== Preparing Environment

Launch Mongo and Config Server:
....
$ docker run --name mongo -d -p 27017:27017 mongo
$ docker run -d --name=config-service -p 8888:8888 msvcdojo/config-service:0.0.1
....

=== Building Profiles Service
Create a basic web Service with the name *profiles-service*.

In the *build.gradle* add additional dependency:
[source,groovy,indent=0]
.profiles-service/build.gradle
----
include::{sourcedir}/solution/profiles-service/build.gradle[tags=mongo]
----

WARNING: Under construction

Add a `Profile` entity describing a document that will be stored in the Database:

[source,java,indent=0]
.src/main/java/msvcdojo/ProfilesServiceApplication.java
----
include::{sourcedir}/solution/profiles-service/src/main/java/msvcdojo/ProfilesServiceApplication.java[tags=ProfilePhoto]
----

Add a PhotoResource. We're going to store binary data in the "files" section
of MongoDB.

[source,java,indent=0]
.src/main/java/msvcdojo/ProfilesServiceApplication.java
----
include::{sourcedir}/solution/profiles-service/src/main/java/msvcdojo/ProfilesServiceApplication.java[tags=PhotoResource]
----

Now it's time to add a data repository description with it's "verbs":

[source,java,indent=0]
.src/main/java/msvcdojo/ProfilesServiceApplication.java
----
include::{sourcedir}/solution/profiles-service/src/main/java/msvcdojo/ProfilesServiceApplication.java[tags=ProfilePhotoRepository]
----

The repository is annotated with `@RepositoryRestResource` making it a REST controller
out of the box. This exposes, in part, GET method to retrieve a list of stored items and
a POST method to insert new items.

We're going to add a REST controller that will allow us to insert a photo (large
binary file) with any arbitrary key by posting data into the URL that looks like
this: `http://host/profiles/{key}/photos`

Create a rest controller with the mapping `/profiles/{key}/photos`:

[source,java,indent=0]
.src/main/java/msvcdojo/ProfilesServiceApplication.java
----
include::{sourcedir}/solution/profiles-service/src/main/java/msvcdojo/ProfilesServiceApplication.java[tags=controller]
----

Add a handler that will process POST requests:

[source,java,indent=0,options="nowrap"]
.src/main/java/msvcdojo/ProfilesServiceApplication.java
----
include::{sourcedir}/solution/profiles-service/src/main/java/msvcdojo/ProfilesServiceApplication.java[tags=insertPhoto]
----

Follow the solution further ...

WARNING: For demo purposes only our service is going to clean up data on start.

The cleanup is executed by `CommandLineRunner` lambda:

[source,java,indent=0,options="nowrap"]
.src/main/java/msvcdojo/ProfilesServiceApplication.java
----
include::{sourcedir}/solution/profiles-service/src/main/java/msvcdojo/ProfilesServiceApplication.java[tags=cleanup]
----

=== Play time

Let's add some data. One profile and one photo for that profile:
[source,text,options="nowrap"]
....
$ gradlew clean prepDocker
$ java -jar -Dconfig-service.uri=http://dockerhost:8888 -Dmongoserver=dockerhost build\libs\profiles-service-0.0.1.jar
$ echo { "key":"john", "fullName":"John Smith" } | curl -H "Content-Type: application/json" -d @- http://localhost:8101/profiles
{{
  "fullName" : "John Smith",
  "key" : "john",
  "photoCount" : 0,
  "_links" : {
    "self" : {
      "href" : "http://localhost:8101/profiles/john"
    },
    "profile" : {
      "href" : "http://localhost:8101/profiles/john"
    },
    "photos" : {
      "href" : "http://localhost:8101/profiles/john/photos"
    }
  }
}
$ curl -F "file=@../../../misc/face.png" http://localhost:8101/profiles/john/photos
{
  "fullName" : "John Smith",
  "key" : "john",
  "photoCount" : 1
}
....

Let's check what photos are stored for a profile:
....
$ curl http://localhost:8101/profiles/john/photos
[ {
  "content" : "john0",
  "links" : [ {
    "rel" : "john0",
    "href" : "http://localhost:8101/profiles/john/photos/john0/photo"
  } ]
} ]
....

Navigate in your browser of choice to the URL provided by the last response and you
should see the uploaded picture.

== Bonus

* Explore the contents of MongoDB by launching Mongo Express web client in docker
and navigating to `http://dockerhost:8081`:
....
$ docker run -d -p 8081:8081 --link mongo:mongo knickers/mongo-express
....
