server:
  port: ${PORT:8101}

#info:
#  build:
#    name: ${name}
#    description: ${description}
#    version: ${version}

spring:
  data:
    mongodb:
      host: ${mongoserver:localhost}
      port: 27017

