:kata_dir: kata1
:sourcedir: ../../../{kata_dir}
include::../header.adoc[]

// include::../header.adoc[]

== Building Simple Web Service with Spring Boot

WARNING: Make sure you have your development environment configured.

In this exercise you are going to create a simple REST web service using Spring Boot.

TIP: You can skip this step if you feel you have a good understanding of Spring Boot.
The rest of the course assume you have a good knowledge of the principles of Spring Boot.

== Step-by-step instructions to bootstrap the project

. Go to Spring Starter https://start.spring.io/
. Select the following options:
.. *Gradle Project*
.. Spring Boot *1.3.2*
.. Group: *msvcdojo*
.. Artifact: *mysvc*
.. Select in "Search for Dependencies":
... *Web*
... *Actuator*
... *Actuator Docs*
.. Click button *Generate Project*
. Download project and expand the archive
. Open in IntelliJ as a Gradle project

=== Let's explore. modify and configure
The project contains an entry point in the _MysvcApplication.java_ file:

[source,java,indent=0]
.MysvcApplication.java
----
include::{sourcedir}/solution/mysvc/src/main/java/msvcdojo/MysvcApplication.java[tags=code]
----

We're going to add a basic REST controller by creating the following class in _MysvcApplication.java_ file:

[source,java,indent=0]
.MysvcApplication.java
----
include::{sourcedir}/solution/mysvc/src/main/java/msvcdojo/MysvcApplication.java[tags=controller]
----

Going forward we're going to use YAML files to provide properties for our services.
Rename the *_mysvc/src/main/resources/application.properties_* file into *_mysvc/src/main/resources/application.yml_*.
Let's expose additional information in our *healthcheck* output. Put the following in the *_application.yml_* file:

[source,yaml,indent=0]
.application.yml
----
include::{sourcedir}/solution/mysvc/src/main/resources/application.yml[]
----

Let's replace Tomcat, that was provided as a default application container, with Jetty.
Replace the following line in *_mysvc/build.gradle_*:

[source,groovy,indent=0]
----
compile('org.springframework.boot:spring-boot-starter-web')
----

With the following block:
[source,groovy,indent=0]
.build.gradle
----
include::{sourcedir}/solution/mysvc/build.gradle[tags=jetty]
----

=== What about tests?

Let's add a unit test that validates the controller:

[source,java,indent=0]
.HomeControllerTest.java
----
include::{sourcedir}/solution/mysvc/src/test/java/msvcdojo/HomeControllerTest.java[tags=test]
----

Let's add some integration test:

[source,java,indent=0]
.HomeControllerIT.java
----
include::{sourcedir}/solution/mysvc/src/test/java/msvcdojo/HomeControllerIT.java[tags=test]
----

We'd like to ask JUnit to generate reports for us. Add the following to *_build.gradle_*:

[source,groovy,indent=0]
.build.gradle
----
include::{sourcedir}/solution/mysvc/build.gradle[tags=jetty]
----

Now it's time to run the tests:
----
$ gradlew test
...
Results: SUCCESS (2 tests, 2 successes, 0 failures, 0 skipped)
----

And, in case you'd like to get a Web report, open the following file in your browser:
----
build\reports\tests\index.html
----

== Build and launch
Build the service:
----
$ cd mysvc
$ gradlew build
----
Note that this command will build the code and run all the necessary tests.

Lauch it the service:
----
$ java -jar build\libs\mysvc-0.0.1.jar
----

The following output you'll on the screen.

[source,text,options="nowrap"]
----
include::bootRun.txt[]
----
<1> Listening port of the web service
<2> List of available end-points that Actuator provides for you for free.

== Play time

=== Healthcheck

Let's health-check our brand new service:

----
$ curl http://localhost:8080/health
----

The output of this CURL command will look like this:

[source,json,indent=0]
----
{
  "status": "UP",
  "diskSpace": {
    "status": "UP",
    "total": 255219200000,
    "free": 70534836224,
    "threshold": 10485760
  }
}
----

See that the *status* value is *UP*. This will be our indication that the service is healthy.
This endpoint can be extended and your application can provide more or less information
based on the needs of your projects.

=== Shutdown

Actuator is not enabling a couple of "dangerous" end-points. One of them is the
one that the automation infrastructure may use to shutdown the service.

You can send an empty POST request to this endpoint for the service gracefully
shutdown itself.

----
$ curl -d {} http://localhost:8080/shutdown
----

=== End-point documentation

The fact that the Actuator-docs package was included in your artifact, your service
has received an additional end point that provides embedded documentation for the
other actuator-provided end points.

You can access this documentation by navigating to the following url:
icon:external-link[link="http://localhost:8080/docs/", window="_blank"]
http://localhost:8080/docs/

Going forward you will not need this dependency so you can remove this line from the
*_build.gradle_*:

[source,groovy,indent=0]
.build.gradle
----
include::{sourcedir}/solution/mysvc/build.gradle[tags=actuator-docs]
----

== Bonus

You can read more about all this:

* http://docs.spring.io/spring-boot/docs/current/reference/htmlsingle/#production-ready[Spring Boot Reference Guide^]
* https://spring.io/guides/gs/spring-boot/[Building an Application with Spring Boot^] guide.
