server:
  port: ${PORT:8122}

sqlserver: localhost

spring:
  jpa:
    database: MYSQL
    hibernate:
      ddl-auto: validate

  datasource:
    url: jdbc:mysql://${sqlserver}:3306/demo
    username: demo_user
    password: demo_pass
    driver-class-name: com.mysql.jdbc.Driver