// :linkcss:
:icons: font
:source-highlighter: coderay
:kata_dir: kata3
:sourcedir: ../../../{kata_dir}

== Web Service using mySql DB

== Preparation
1. Create a basic web Service with the name *accounts-service*.

2. Launch mySql server in Docker:
[source,text,options="nowrap"]
----
$ docker run --name demo-mysql -e MYSQL_ROOT_PASSWORD=password -e MYSQL_DATABASE=demo -e MYSQL_USER=demo_user -e MYSQL_PASSWORD=demo_pass -p 3306:3306 -d mysql:5.6
----

Validate that mySql has successfully started by looking into docker container logs:
----
$ docker logs demo-mysql
...
2016-01-25 04:52:44 1 [Note] mysqld: ready for connections.
Version: '5.6.28'  socket: '/var/run/mysqld/mysqld.sock'  port: 3306  MySQL Community Server (GPL)
----

=== Adding JPA

NOTE: The solution to this exercise part can be found in *solution1* folder.

Add data model:
[source,java,indent=0]
.src/main/java/msvcdojo/AccountsServiceApplication.java
----
include::{sourcedir}/solution1/accounts-service/src/main/java/msvcdojo/AccountsServiceApplication.java[tags=data-model]
----

Add data repository:
[source,java,indent=0]
.src/main/java/msvcdojo/AccountsServiceApplication.java
----
include::{sourcedir}/solution1/accounts-service/src/main/java/msvcdojo/AccountsServiceApplication.java[tags=data-repository]
----

Add JPA dependency to build.
[source,groovy,indent=0]
.build.gradle
----
include::{sourcedir}/solution1/accounts-service/build.gradle[tags=jpa]
----

Add SQL connection to application.yml
[source,yaml,indent=0]
.src/main/resouces/application.yml
----
include::{sourcedir}/solution1/accounts-service/src/main/resources/application.yml[tags=jpa]
----

NOTE: You're free to run your service, but, if you don't have DB schema provisioned,
you're going to see a spectacular crash of your service with an exception that may
look like this: *HibernateException: Missing table: account*

=== Adding Flyway DB migrations (Part 1)

We can not yet run the application because the database doesn't exist yet.
So we're going to use a best-practice of Continuous Delivery - DB schema versioning
and migrations.

NOTE: In real life you may want to mange DB migrations separately from the
source code of the service. Mostly make sure that the DB migrations are not
happening on the service launch but as a separate *intentionnal* process.

_1. Add plugin dependency
[source,groovy,indent=0]
.build.gradle
----
include::{sourcedir}/solution1/accounts-service/build.gradle[tags=flyway-plugin-dep]
----
_2. Add plugin
[source,groovy,indent=0]
.build.gradle
----
include::{sourcedir}/solution1/accounts-service/build.gradle[tags=flyway-plugin]
----
_3. Add Flyway migrations build section
[source,groovy,indent=0]
.build.gradle
----
include::{sourcedir}/solution1/accounts-service/build.gradle[tags=flyway]
----
_4. Add V1 migration - initialization
[source,text,indent=0]
.src/main/resources/db/migration/V1__init.sql
----
include::{sourcedir}/solution1/accounts-service/src/main/resources/db/migration/V1__init.sql[]
----

IMPORTANT: Avoid putting data and configuration in the schema migrations at
all costs. This example is for demo purposes only.

_5. Apply V1 migration
....
$ gradlew flywayMigrate
....

If, at this moment, you'll check the mySql server, you'll find a "demo" database
with a single row of data like this:

[format="csv", options="header"]
|===
id,username
1,john
|===

==== Play time (part 1)

Now it's time to run the service.
....
$ java -jar build\libs\accounts-service-0.0.1.jar
....

NOTE: You can use your favorite browser to navigate REST endpoints by following
icon:external-link[link="http://localhost:8100/", window="_blank"]
http://localhost:8100/

Let's hit the root endpoint:
....
$ curl http://localhost:8100/
....

You'll see the following output:
[source,json,indent=0]
....
{
  "_links" : {
    "accounts" : {
      "href" : "http://localhost:8100/accounts{?page,size,sort}",
      "templated" : true
    },
    "profile" : {
      "href" : "http://localhost:8100/profile"
    }
  }
}
....

Note the response is coming in the HATEOAS (Hypermedia as the Engine of
Application State) which is a constraint of the http://en.wikipedia.org/wiki/HATEOAS[REST application architecture^].

NOTE: Read more on HATEOAS in https://spring.io/understanding/HATEOAS[Understanding HATEOAS^] Spring guide.

Following the *accounts* path:
....
$ curl http://localhost:8100/accounts
....

Produces the following result:
[source,json,indent=0]
....
{
  "_embedded" : {
    "accounts" : [ {
      "username" : "john",
      "_links" : {
        "self" : {
          "href" : "http://localhost:8100/accounts/1"
        },
        "account" : {
          "href" : "http://localhost:8100/accounts/1"
        }
      }
    } ]
  },
  "_links" : {
    "self" : {
      "href" : "http://localhost:8100/accounts"
    },
    "profile" : {
      "href" : "http://localhost:8100/profile/accounts"
    },
    "search" : {
      "href" : "http://localhost:8100/accounts/search"
    }
  },
  "page" : {
    "size" : 20,
    "totalElements" : 1,
    "totalPages" : 1,
    "number" : 0
  }
}
....

To get information about a single *account* you navigate to the item's resource URI:
....
$ curl http://localhost:8100/accounts/1
....

The result will look like this:
....
{
  "username" : "john",
  "_links" : {
    "self" : {
      "href" : "http://localhost:8100/accounts/1"
    },
    "account" : {
      "href" : "http://localhost:8100/accounts/1"
    }
  }
}
....

Now let's, in fact, try to use this service for some real work by adding
more records to the database:

[source,text,options="nowrap"]
....
$ echo {"username" : "dave"} | curl -H "Content-type:application/json" -d @- http://localhost:8100/accounts
....

This produces the following output:
[source,json,indent=0]
....
{
  "username" : "dave",
  "_links" : {
    "self" : {
      "href" : "http://localhost:8100/accounts/2"
    },
    "account" : {
      "href" : "http://localhost:8100/accounts/2"
    }
  }
}
....

Let's run a query to find the new record:
....
$ curl http://localhost:8100/accounts/search/findByUsername?username=dave
....

If, you've followed all the steps carefully, you'll be rewarded with the following
result:
[source,json,indent=0]
....
{
  "_embedded" : {
    "accounts" : [ {
      "username" : "dave",
      "_links" : {
        "self" : {
          "href" : "http://localhost:8100/accounts/2"
        },
        "account" : {
          "href" : "http://localhost:8100/accounts/2"
        }
      }
    } ]
  },
  "_links" : {
    "self" : {
      "href" : "http://localhost:8100/accounts/search/findByUsername?username=dave"
    }
  }
}
....

=== Adding Flyway DB migrations (Part 2)

In the normal lifecycle of the live system you're going to modify the data models
multiple times and will have a need to migrate the database alongside.

Here we're going to add a new field *role* to the *account* table where we're
going to track their roles.

NOTE: The solution to this exercise part can be found in *solution2* folder.

Add a second migration (to V2):
[source,text,indent=0]
.src/main/resources/db/migration/V2__add_role.sql
----
include::{sourcedir}/solution2/accounts-service/src/main/resources/db/migration/V2__add_role.sql[]
----

Add the *role* mapping to the data model:
[source,java,indent=0]
.src/main/java/msvcdojo/AccountsServiceApplication.java
----
include::{sourcedir}/solution2/accounts-service/src/main/java/msvcdojo/AccountsServiceApplication.java[tags=data-model]
----

And allow search by this new field in the data repository class:
[source,java,indent=0]
.src/main/java/msvcdojo/AccountsServiceApplication.java
----
include::{sourcedir}/solution2/accounts-service/src/main/java/msvcdojo/AccountsServiceApplication.java[tags=findByRole]
----

Now, when you'll start the service, the DB will look like this:

[format="csv", options="header"]
|===
id,username,role
1,john,admin
2,dave,
|===

Let's try to query by the new field:
....
$ curl http://localhost:8100/accounts/search/findByRole?role=admin
....

And the result will look like this:
[source,json,indent=0]
....
{
  "_embedded" : {
    "accounts" : [ {
      "username" : "john",
      "role"     : "admin",
      "_links" : {
        "self" : {
          "href" : "http://localhost:8100/accounts/1"
        },
        "account" : {
          "href" : "http://localhost:8100/accounts/1"
        }
      }
    } ]
  },
  "_links" : {
    "self" : {
      "href" : "http://localhost:8100/accounts/search/findByRole?role=admin"
    }
  }
}
....

=== Adding tests

Don't forget about tests.

WARNING: tests that use external Database are part of the integration and E2E
(end-to-end) test suits. They require external infrastructure and data seeding.
They are prone to failures and hard to maintain.

Here is an example of a test that validates presence of the data in the Database
after migration:

[source,java,indent=0]
.src/test/java/msvcdojo/AccountsServiceApplicationTests.java
----
include::{sourcedir}/solution2/accounts-service/src/test/java/msvcdojo/AccountsServiceApplicationTests.java[tags=test]
----

=== Dockerize Accounts Service

....
$ gradlew prepDocker
$ docker build -t msvcdojo/accounts-service:0.0.1 build/docker
....

== Bonus

* Read more on this topic in https://spring.io/guides/gs/accessing-data-rest/[Accessing JPA Data with REST^] guide.
* More on Flyway and http://flywaydb.org/getstarted/why.html[Why database migrations?^]
* You can get very crafty with http://docs.spring.io/spring-boot/docs/current/reference/html/common-application-properties.html[Flyway parameters^] in YAML config
